source 'https://github.com/CocoaPods/Specs.git'

target 'MBSimpleLoadingIndicator', :exclusive => true do
  pod "MBSimpleLoadingIndicator", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MBSimpleLoadingIndicator", :path => "../"

  
end
